# Configuración del Backend (Donde se guarda el contenido)
backend:
  name: github # Usamos GitHub
  repo: Pqblo26/shirov2-awards # Reemplaza con tu usuario/repositorio si es diferente
  branch: main # La rama donde se guardarán los cambios
  # commit_messages: # Opcional: Personaliza mensajes de commit
  #   create: 'Create {{collection}} “{{slug}}”'
  #   update: 'Update {{collection}} “{{slug}}”'
  #   delete: 'Delete {{collection}} “{{slug}}”'
  #   uploadMedia: 'Upload “{{path}}”'
  #   deleteMedia: 'Delete “{{path}}”'

# Configuración de Media (Imágenes, etc.)
media_folder: "public/images/uploads" # Ruta relativa a la raíz del proyecto donde se guardan las imágenes
public_folder: "/images/uploads" # Ruta pública para acceder a las imágenes en la web

# Configuración de Colecciones (Tipos de Contenido)
collections:
  # --- Colección para las Traducciones ---
  - name: "traducciones" # Identificador interno (¡importante!)
    label: "Traducciones" # Nombre visible en la interfaz del CMS
    label_singular: "Traducción" # Nombre singular
    folder: "content/traducciones" # Carpeta donde se guardarán los archivos .md (relativa a la raíz)
    create: true # Permitir crear nuevas traducciones
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Cómo se generará el nombre del archivo (ej: 2025-04-06-titulo-manga)
    # Define los campos editables para cada traducción
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "imageUrl", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", field: {label: Tag, name: tag, widget: string}, required: false }
      - label: "Estado"
        name: "status"
        widget: "select"
        options: ["En Progreso", "Finalizado", "Pausado", "Cancelado"]
        default: "En Progreso"
        required: false
      - label: "Categoría Principal" # Se mantiene por si se usa en otro sitio
        name: "mainCategory"
        widget: "select"
        options: ["Anime", "Donghua", "Otros"]
        required: false
      # --- Campo 'format' MODIFICADO ---
      # Cambiado de 'select' a 'string' para texto libre (ej: MKV Softsubs)
      - label: "Formato (Release)" # Etiqueta actualizada para claridad
        name: "format"
        widget: "string" # Cambiado a string
        required: false
        hint: "Ej: MKV Softsubs, MP4 Hardsubs, BDrip" # Añadido hint
      - { label: "Fuente Original / Grupo", name: "source", widget: "string", required: false, hint: "Nombre del grupo o fuente original si aplica" } # Añadido hint
      - { label: "Sinopsis / Extracto Corto", name: "excerpt", widget: "text", required: false }

      # --- NUEVOS CAMPOS TÉCNICOS ---
      - label: "Resolución"
        name: "resolution"
        widget: "string"
        required: false
        hint: "Ej: 1920x1080, 1280x720"
      - label: "Codec de Video"
        name: "videoCodec"
        widget: "string"
        required: false
        hint: "Ej: H.265/HEVC, H.264/AVC"
      - label: "Codec de Audio"
        name: "audioCodec"
        widget: "string"
        required: false
        hint: "Ej: AAC (Japonés), FLAC"
      - label: "Recursos Externos"
        name: "externalResources"
        widget: "string"
        required: false
        hint: "Enlace a web oficial, MyAnimeList, etc. o N/A"

      # --- NUEVO CAMPO LISTA PARA DESCARGAS ---
      - label: "Enlaces de Descarga"
        name: "downloads"
        widget: "list"
        label_singular: "Enlace de Descarga"
        summary: "{{fields.quality}} [{{fields.format}}] - {{fields.server}}" # Resumen visible en la lista
        required: false
        fields: # Campos para cada objeto dentro de la lista 'downloads'
          - { label: "Calidad", name: "quality", widget: "string", required: false, hint: "Ej: 1080p, 720p, BD" }
          - { label: "Formato (Archivo)", name: "format", widget: "string", required: false, hint: "Ej: MKV, MP4" }
          - { label: "Servidor", name: "server", widget: "string", required: false, hint: "Ej: Mega, Drive, Torrent" }
          - { label: "URL", name: "url", widget: "string", hint: "El enlace directo de descarga o magnet link" } # URL es el único campo requerido dentro de un enlace
          - { label: "Notas Adicionales", name: "notes", widget: "string", required: false, hint: "Ej: v2, Parche, Incluye extras" }

      # Contenido principal de la traducción usando Markdown
      # Aunque no se muestra en SingleTranslationPage v6/v7, se mantiene aquí por si se usa en otro lugar o futuro.
      - { label: "Contenido Principal (Markdown)", name: "body", widget: "markdown", required: false }

  # --- Aquí añadirías otras colecciones en el futuro ---
  # - name: "premios"
  #   label: "Premios"
  #   ...etc...
