# Configuración del Backend
backend:
  name: github
  repo: Pqblo26/shirov2-awards
  branch: main
  # commit_messages: ... (opcional)

# Configuración de Media
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Configuración de Colecciones
collections:
  # --- Colección para las Traducciones ---
  - name: "traducciones"
    label: "Traducciones"
    label_singular: "Traducción"
    folder: "content/traducciones"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "imageUrl", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", field: {label: Tag, name: tag, widget: string}, required: false }
      - label: "Estado"
        name: "status"
        widget: "select"
        options: ["En Progreso", "Finalizado", "Pausado", "Cancelado"]
        default: "En Progreso"
        required: false
      - label: "Categoría Principal"
        name: "mainCategory"
        widget: "select"
        options: ["Anime", "Donghua", "Otros"]
        required: false

      # --- Campos con opción "Otro" ---

      # Formato (Release)
      - label: "Formato (Release)"
        name: "format_select" # Renombrado para claridad
        widget: "select"
        options: ["MKV Softsubs", "MP4 Hardsubs", "MKV Hardsubs", "BDrip", "WebRip", "Otro"] # Añadida opción "Otro"
        required: false
      - label: "Especificar Otro Formato"
        name: "format_other" # Nuevo campo condicional
        widget: "string"
        required: false
        condition: { field: "format_select", value: "Otro" } # Aparece si se selecciona "Otro"

      # Fuente Original / Grupo
      - label: "Fuente Original / Grupo"
        name: "source_select" # Renombrado
        widget: "select"
        options: ["ShiroSubs", "Fuente Oficial", "Otro Grupo", "N/A", "Otro"] # Añadida opción "Otro"
        required: false
      - label: "Especificar Otra Fuente/Grupo"
        name: "source_other" # Nuevo campo condicional
        widget: "string"
        required: false
        condition: { field: "source_select", value: "Otro" }

      # Resolución
      - label: "Resolución"
        name: "resolution_select" # Renombrado
        widget: "select"
        options: ["1920x1080", "1280x720", "2560x1440", "3840x2160", "SD", "Otro"] # Añadida opción "Otro"
        required: false
      - label: "Especificar Otra Resolución"
        name: "resolution_other" # Nuevo campo condicional
        widget: "string"
        required: false
        condition: { field: "resolution_select", value: "Otro" }

      # Codec de Video
      - label: "Codec de Video"
        name: "videoCodec_select" # Renombrado
        widget: "select"
        options: ["H.265/HEVC", "H.264/AVC", "AV1", "VP9", "Otro"] # Añadida opción "Otro"
        required: false
      - label: "Especificar Otro Codec Video"
        name: "videoCodec_other" # Nuevo campo condicional
        widget: "string"
        required: false
        condition: { field: "videoCodec_select", value: "Otro" }

      # Codec de Audio
      - label: "Codec de Audio"
        name: "audioCodec_select" # Renombrado
        widget: "select"
        options: ["AAC", "FLAC", "Opus", "AC3", "DTS", "Otro"] # Añadida opción "Otro"
        required: false
      - label: "Especificar Otro Codec Audio"
        name: "audioCodec_other" # Nuevo campo condicional
        widget: "string"
        required: false
        condition: { field: "audioCodec_select", value: "Otro" }

      # --- Campos que SIGUEN SIENDO Texto/String ---
      - { label: "Sinopsis / Extracto Corto", name: "excerpt", widget: "text", required: false }
      - label: "Recursos Externos"
        name: "externalResources"
        widget: "string"
        required: false
        hint: "Enlace a web oficial, MyAnimeList, etc. o N/A"

      # --- Campo Lista para Descargas (con modificaciones internas) ---
      - label: "Enlaces de Descarga"
        name: "downloads"
        widget: "list"
        label_singular: "Enlace de Descarga"
        summary: "{{fields.quality_select}} [{{fields.format_select}}] - {{fields.server_select}}" # Actualizado summary
        required: false
        fields:
          # Calidad (Descarga)
          - label: "Calidad"
            name: "quality_select" # Renombrado
            widget: "select"
            options: ["1080p", "720p", "480p", "BD", "Web-DL", "Otro"] # Añadida opción "Otro"
            required: false
          - label: "Especificar Otra Calidad"
            name: "quality_other" # Nuevo campo condicional
            widget: "string"
            required: false
            condition: { field: "quality_select", value: "Otro" }

          # Formato (Archivo Descarga)
          - label: "Formato (Archivo)"
            name: "format_select" # Renombrado
            widget: "select"
            options: ["MKV", "MP4", "AVI", "Otro"] # Añadida opción "Otro"
            required: false
          - label: "Especificar Otro Formato Archivo"
            name: "format_other" # Nuevo campo condicional
            widget: "string"
            required: false
            condition: { field: "format_select", value: "Otro" }

          # Servidor (Descarga)
          - label: "Servidor"
            name: "server_select" # Renombrado
            widget: "select"
            options: ["Mega", "Google Drive", "OneDrive", "Torrent", "Descarga Directa", "Pixeldrain", "Otro"] # Añadida opción "Otro"
            required: false
          - label: "Especificar Otro Servidor"
            name: "server_other" # Nuevo campo condicional
            widget: "string"
            required: false
            condition: { field: "server_select", value: "Otro" }

          # Campos que siguen siendo string dentro de downloads
          - { label: "URL", name: "url", widget: "string", hint: "El enlace directo de descarga o magnet link" }
          - { label: "Notas Adicionales", name: "notes", widget: "string", required: false, hint: "Ej: v2, Parche, Incluye extras" }

      # Contenido principal (Markdown)
      - { label: "Contenido Principal (Markdown)", name: "body", widget: "markdown", required: false }

  # --- Otras colecciones (ejemplo) ---
  # - name: "premios"
  #   label: "Premios"
  #   ...etc...
