# Configuración del Backend
backend:
  name: github
  repo: Pqblo26/shirov2-awards
  branch: main
  # commit_messages: ... (opcional)

# Configuración de Media
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Configuración de Colecciones
collections:
  # --- Colección para las Traducciones ---
  - name: "traducciones"
    label: "Traducciones"
    label_singular: "Traducción"
    folder: "content/traducciones"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "imageUrl", widget: "image", required: false }
      - { label: "Tags (Adicionales)", name: "tags", widget: "list", summary: "{{fields.tag}}", field: {label: Tag, name: tag, widget: string}, required: false, hint: "Tags extra aparte de estado, categoría, formato, etc." }
      - label: "Estado"
        name: "status"
        widget: "select"
        options: ["En Progreso", "Finalizado", "Pausado", "Cancelado"]
        default: "En Progreso"
        required: false

      # --- NUEVO CAMPO: Progreso ---
      - label: "Progreso (%)"
        name: "progress"
        widget: "number"
        required: false
        value_type: "int" # Guardar como entero
        min: 0
        max: 100
        step: 5 # Incrementos de 5%
        hint: "Porcentaje de completado (0-100). Usado para el widget 'Trabajando Actualmente'."

      - label: "Categoría Principal"
        name: "mainCategory"
        widget: "select"
        options: ["Anime", "Donghua", "Otros"]
        required: false
      - label: "Formato (TV/Película/OVA...)"
        name: "format_select"
        widget: "select"
        options: ["TV", "OVA", "Especial", "Película", "Otro"]
        required: false
      - label: "Especificar Otro Formato"
        name: "format_other"
        widget: "string"
        required: false
        condition: { field: "format_select", value: "Otro" }
      - label: "Especificaciones (MKV/MP4...)"
        name: "specification_select"
        widget: "select"
        options: ["MKV", "MP4", "AVI", "Otro"]
        required: false
      - label: "Especificar Otra Especificación"
        name: "specification_other"
        widget: "string"
        required: false
        condition: { field: "specification_select", value: "Otro" }
      - label: "Fuente Original / Grupo"
        name: "source_select"
        widget: "select"
        options: ["ShiroSubs", "Fuente Oficial", "Otro Grupo", "N/A", "Otro"]
        required: false
      - label: "Especificar Otra Fuente/Grupo"
        name: "source_other"
        widget: "string"
        required: false
        condition: { field: "source_select", value: "Otro" }
      - label: "Resolución"
        name: "resolution_select"
        widget: "select"
        options: ["1920x1080", "1280x720", "2560x1440", "3840x2160", "SD", "Otro"]
        required: false
      - label: "Especificar Otra Resolución"
        name: "resolution_other"
        widget: "string"
        required: false
        condition: { field: "resolution_select", value: "Otro" }
      - label: "Codec de Video"
        name: "videoCodec_select"
        widget: "select"
        options: ["H.265/HEVC", "H.264/AVC", "AV1", "VP9", "Otro"]
        required: false
      - label: "Especificar Otro Codec Video"
        name: "videoCodec_other"
        widget: "string"
        required: false
        condition: { field: "videoCodec_select", value: "Otro" }
      - label: "Codec de Audio"
        name: "audioCodec_select"
        widget: "select"
        options: ["AAC", "FLAC", "Opus", "AC3", "DTS", "Otro"]
        required: false
      - label: "Especificar Otro Codec Audio"
        name: "audioCodec_other"
        widget: "string"
        required: false
        condition: { field: "audioCodec_select", value: "Otro" }
      - { label: "Sinopsis / Extracto Corto", name: "excerpt", widget: "text", required: false }
      - label: "Recursos Externos"
        name: "externalResources"
        widget: "string"
        required: false
        hint: "Enlace a web oficial, MyAnimeList, etc. o N/A"
      - label: "Enlaces de Descarga"
        name: "downloads"
        widget: "list"
        # ... (resto de la configuración de downloads) ...
        label_singular: "Enlace de Descarga"
        summary: "{{fields.quality_select}} [{{fields.format_select}}] - {{fields.server_select}}"
        required: false
        fields:
          - { label: "Calidad", name: "quality_select", widget: "select", options: ["1080p", "720p", "480p", "BD", "Web-DL", "Otro"], required: false }
          - { label: "Especificar Otra Calidad", name: "quality_other", widget: "string", required: false, condition: { field: "quality_select", value: "Otro" } }
          - { label: "Formato (Archivo)", name: "format_select", widget: "select", options: ["MKV", "MP4", "AVI", "Otro"], required: false }
          - { label: "Especificar Otro Formato Archivo", name: "format_other", widget: "string", required: false, condition: { field: "format_select", value: "Otro" } }
          - { label: "Servidor", name: "server_select", widget: "select", options: ["Mega", "Google Drive", "OneDrive", "Torrent", "Descarga Directa", "Pixeldrain", "Otro"], required: false }
          - { label: "Especificar Otro Servidor", name: "server_other", widget: "string", required: false, condition: { field: "server_select", value: "Otro" } }
          - { label: "URL", name: "url", widget: "string", hint: "El enlace directo de descarga o magnet link" }
          - { label: "Notas Adicionales", name: "notes", widget: "string", required: false, hint: "Ej: v2, Parche, Incluye extras" }

      - { label: "Contenido Principal (Markdown)", name: "body", widget: "markdown", required: false }

  # --- Otras colecciones (ejemplo) ---
  # - name: "premios"
  #   label: "Premios"
  #   ...etc...
