# Configuración del Backend
backend:
  name: github
  repo: Pqblo26/shirov2-awards
  branch: main

# Configuración de Media
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Configuración de Colecciones
collections:
  # --- Colección para las Traducciones ---
  - name: "traducciones"
    label: "Traducciones (General)"
    label_singular: "Traducción"
    folder: "content/traducciones"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "imageUrl", widget: "image", required: false }
      - { label: "Tags (Adicionales)", name: "tags", widget: "list", summary: "{{fields.tag}}", field: {label: Tag, name: tag, widget: string}, required: false, hint: "Tags extra aparte de estado, categoría, formato, etc." }
      - { label: "Estado (General)", name: "status", widget: "select", options: ["En Progreso", "Finalizado", "Pausado", "Cancelado", "Próximamente"], required: false }
      - { label: "Categoría Principal", name: "mainCategory", widget: "select", options: ["Anime", "Donghua", "Otros"], required: false }
      - { label: "Formato (TV/Película/OVA...)", name: "format_select", widget: "select", options: ["TV", "OVA", "Especial", "Película", "Otro"], required: false } # Nota: TV Short se maneja en el código, no necesita estar aquí si no es un valor directo del CMS
      - { label: "Especificar Otro Formato", name: "format_other", widget: "string", required: false, condition: { field: "format_select", value: "Otro" } }
      - { label: "Especificaciones (MKV/MP4...)", name: "specification_select", widget: "select", options: ["MKV", "MP4", "AVI", "Otro"], required: false }
      - { label: "Especificar Otra Especificación", name: "specification_other", widget: "string", required: false, condition: { field: "specification_select", value: "Otro" } }
      - { label: "Fuente Original / Grupo", name: "source_select", widget: "select", options: ["ShiroSubs", "Fuente Oficial", "Otro Grupo", "N/A", "Otro"], required: false }
      - { label: "Especificar Otra Fuente/Grupo", name: "source_other", widget: "string", required: false, condition: { field: "source_select", value: "Otro" } }
      - { label: "Resolución", name: "resolution_select", widget: "select", options: ["1920x1080", "1280x720", "2560x1440", "3840x2160", "SD", "Otro"], required: false }
      - { label: "Especificar Otra Resolución", name: "resolution_other", widget: "string", required: false, condition: { field: "resolution_select", value: "Otro" } }
      - { label: "Codec de Video", name: "videoCodec_select", widget: "select", options: ["H.265/HEVC", "H.264/AVC", "AV1", "VP9", "Otro"], required: false }
      - { label: "Especificar Otro Codec Video", name: "videoCodec_other", widget: "string", required: false, condition: { field: "videoCodec_select", value: "Otro" } }
      - label: "Episodios"
        name: "episodeCount"
        widget: "string" # Usamos string para flexibilidad (ej: 12, 24+OVA, Película)
        required: false
        hint: "Ej: 12, 24 + OVA, Película, En emisión"
      - { label: "Sinopsis / Extracto Corto", name: "excerpt", widget: "text", required: false }
      - { label: "Recursos Externos", name: "externalResources", widget: "string", required: false, hint: "Enlace a web oficial, MyAnimeList, etc. o N/A" }
      - { label: "Enlaces de Descarga", name: "downloads", widget: "list", label_singular: "Enlace de Descarga", summary: "{{fields.quality_select}} [{{fields.format_select}}] - {{fields.server_select}}", required: false, fields: [ { label: "Calidad", name: "quality_select", widget: "select", options: ["1080p", "720p", "480p", "BD", "Web-DL", "Otro"], required: false }, { label: "Especificar Otra Calidad", name: "quality_other", widget: "string", required: false, condition: { field: "quality_select", value: "Otro" } }, { label: "Formato (Archivo)", name: "format_select", widget: "select", options: ["MKV", "MP4", "AVI", "Otro"], required: false }, { label: "Especificar Otro Formato Archivo", name: "format_other", widget: "string", required: false, condition: { field: "format_select", value: "Otro" } }, { label: "Servidor", name: "server_select", widget: "select", options: ["Mega", "Google Drive", "OneDrive", "Torrent", "Descarga Directa", "Pixeldrain", "Otro"], required: false }, { label: "Especificar Otro Servidor", name: "server_other", widget: "string", required: false, condition: { field: "server_select", value: "Otro" } }, { label: "URL", name: "url", widget: "string", hint: "El enlace directo de descarga o magnet link" }, { label: "Notas Adicionales", name: "notes", widget: "string", required: false, hint: "Ej: v2, Parche, Incluye extras" } ] }
      - { label: "Contenido Principal (Markdown)", name: "body", widget: "markdown", required: false }

  # --- Colección WIP Items ---
  - name: "wip_items"
    label: "Trabajando Actualmente (Widget)"
    label_singular: "Elemento WIP"
    folder: "content/wip"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título / Nombre Tarea", name: "title", widget: "string", hint: "Ej: Manga XYZ - Cap 11, Anime ABC - Ep 05" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - label: "Posición de la Imagen (Punto Focal)"
        name: "image_position_select"
        widget: "select"
        options: # Opciones predefinidas
          - { label: "Centro", value: "center center" }
          - { label: "Arriba", value: "center top" }
          # --- NUEVA OPCIÓN ---
          - { label: "Centro-Arriba", value: "center 25%" } # Posición entre centro y arriba
          # --- FIN NUEVA OPCIÓN ---
          - { label: "Abajo", value: "center bottom" }
          - { label: "Izquierda", value: "left center" }
          - { label: "Derecha", value: "right center" }
          - { label: "Esquina Superior Izquierda", value: "left top" }
          - { label: "Esquina Superior Derecha", value: "right top" }
          - { label: "Esquina Inferior Izquierda", value: "left bottom" }
          - { label: "Esquina Inferior Derecha", value: "right bottom" }
        default: "center center" # Valor por defecto
        required: false
        hint: "Define qué parte de la imagen se prioriza al mostrarla. 'Centro' es el valor por defecto."
      - { label: "Estado del Paso Actual", name: "wip_status", widget: "select", options: ["Traduciendo", "Editando", "Corrigiendo", "Q.C.", "Encoding", "Subiendo", "Otro"], required: false }
      - { label: "Progreso (%)", name: "progress", widget: "number", required: false, value_type: "int", min: 0, max: 100, step: 5, hint: "Porcentaje de completado de esta tarea específica (0-100)." }
      - { label: "Enlace (Opcional)", name: "link", widget: "string", required: false, hint: "Enlace a la página de la traducción principal si aplica (ej: /traducciones/manga-xyz)" }
      - { label: "Orden (Opcional)", name: "order", widget: "number", required: false, value_type: "int", hint: "Número para ordenar manually (menor aparece primero). Si no se usa, se ordenará por defecto." }
      - { label: "Fecha Creación (Automática)", name: "date", widget: "datetime", default: "", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false, hide: true }

  # --- NUEVA COLECCIÓN: Premios ---
  - name: "premios"             # Identificador de la colección
    label: "Premios Shiro Awards" # Nombre visible en el CMS
    label_singular: "Premio"    # Nombre para un solo item
    folder: "content/premios"   # Carpeta donde se guardarán los archivos .md
    create: true                # Permitir crear nuevos premios
    delete: true                # Permitir borrar premios
    slug: "{{slug}}"            # Usar el título como nombre de archivo (o puedes cambiarlo a {{award_category}}-{{winner_name}})
    summary: "{{award_type}} - {{award_category}}: {{winner_name}}" # Resumen visible en la lista del CMS
    fields:                     # Campos para cada premio
      - label: "Tipo de Premio"
        name: "award_type"
        widget: "select"
        options: ["Temporada", "Aspecto Técnico", "Actor de Voz", "Género"]
        required: true
        hint: "Clasifica el premio para agruparlo en la página."
      - label: "Categoría del Premio"
        name: "award_category"
        widget: "string"
        required: true
        hint: "Ej: Mejor Anime de Invierno, Mejor Animación, Acción"
      - label: "Nombre del Ganador"
        name: "winner_name"
        widget: "string"
        required: true
        hint: "Ej: Anime Ejemplo Invierno, Nombre Actor/Actriz"
      - label: "Imagen del Ganador"
        name: "winner_image"
        widget: "image"
        required: false
      - label: "Información Extra"
        name: "winner_extra"
        widget: "string"
        required: false
        hint: "Ej: Estudio MAPPA, Personaje Ejemplo"
      - label: "Color de la Tarjeta"
        name: "display_color"
        widget: "select"
        options: # Asegúrate que estos valores coincidan con las keys en colorStyles de WinnerCard.tsx
          - { label: "Azul (Temporada Invierno)", value: "blue" }
          - { label: "Rosa (Temporada Primavera)", value: "pink" }
          - { label: "Naranja (Temporada Verano)", value: "orange" }
          - { label: "Rojo (Temporada Otoño / Género)", value: "red" }
          - { label: "Amarillo (Aspecto Técnico)", value: "yellow" }
          - { label: "Índigo (Actores Voz)", value: "indigo" }
          - { label: "Gris (Por defecto)", value: "default" } # Opcional, si quieres un color por defecto
        required: true
        default: "default"
      - label: "Orden (Opcional)"
        name: "order"
        widget: "number"
        required: false
        value_type: "int"
        hint: "Número para ordenar manualmente dentro de cada tipo (menor aparece primero)."
      # Podrías añadir más campos si fueran necesarios, como 'year', 'description', etc.